# Generated by Django 5.1.6 on 2026-02-22 02:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("soc", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="agent",
            name="current_cpu",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="agent",
            name="current_disk",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="agent",
            name="current_gpu",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="agent",
            name="current_ram",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="alert",
            name="mitre_tactic",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="alert",
            name="mitre_technique_id",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.CreateModel(
            name="EndpointRisk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.PositiveSmallIntegerField(default=0)),
                ("reasons", models.JSONField(default=list)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "agent",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="endpoint_risk",
                        to="soc.agent",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="soc.organization",
                    ),
                ),
            ],
        ),
    ]
