# Generated by Django 5.1.6 on 2026-02-22 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agent_downloads", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agentrelease",
            name="sha256",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddConstraint(
            model_name="agentrelease",
            constraint=models.UniqueConstraint(
                fields=("platform", "version"), name="unique_release_platform_version"
            ),
        ),
    ]
